import { University } from '../models/university';
import { Student } from '../models/student';

export const universities: University[] = [
  {
      university_id: 1,
      code: 'CU',
      name: 'จุฬาลงกรณ์มหาวิทยาลัย',
  },
  {
      university_id: 2,
      code: 'MU',
      name: 'มหาวิทยาลัยมหิดล',
  },
  {
      university_id: 3,
      code: 'CMU',
      name: 'มหาวิทยาลัยเชียงใหม่',
  },
  {
      university_id: 4,
      code: 'TU',
      name: 'มหาวิทยาลัยธรรมศาสตร์',
  },
  {
      university_id: 5,
      code: 'KU',
      name: 'มหาวิทยาลัยเกษตรศาสตร์',
  },
  {
      university_id: 6,
      code: 'PSU',
      name: 'มหาวิทยาลัยสงขลานครินทร์',
  },
  {
      university_id: 7,
      code: 'KKU',
      name: 'มหาวิทยาลัยขอนแก่น',
  },
  {
      university_id: 8,
      code: 'KMUTT',
      name: 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี',
  },
  {
      university_id: 9,
      code: 'KMUTNB',
      name: 'มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าพระนครเหนือ',
  },
  {
      university_id: 10,
      code: 'KMITL',
      name: 'สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง',
  },
  {
      university_id: 11,
      code: 'NU',
      name: 'มหาวิทยาลัยนเรศวร',
  },
  {
      university_id: 12,
      code: 'SU',
      name: 'มหาวิทยาลัยศิลปากร',
  },
  {
      university_id: 13,
      code: 'SUT',
      name: 'มหาวิทยาลัยเทคโนโลยีสุรนารี',
  }
];


export const students: Student[] = [
  {
      student_id: 67001,
      prefix: 'นาย',
      first_name: 'สมชาย',
      last_name: 'ศรีสวัสดิ์',
  },
  {
      student_id: 67002,
      prefix: 'นางสาว',
      first_name: 'สมหญิง',
      last_name: 'ทองดี',
  },
  {
      student_id: 67003,
      prefix: 'นาย',
      first_name: 'วิชัย',
      last_name: 'รัตนมณี',
  },
  {
      student_id: 67004,
      prefix: 'นางสาว',
      first_name: 'วราภรณ์',
      last_name: 'จันทรา',
  },
  {
      student_id: 67005,
      prefix: 'นาย',
      first_name: 'สุริยา',
      last_name: 'ทองสุข',
  },
  {
      student_id: 67006,
      prefix: 'นางสาว',
      first_name: 'กานดา',
      last_name: 'นาคเจริญ',
  },
  {
      student_id: 67007,
      prefix: 'นาย',
      first_name: 'ประสิทธิ์',
      last_name: 'สิงห์โต',
  },
  {
      student_id: 67008,
      prefix: 'นาย',
      first_name: 'ปรีชา',
      last_name: 'เสือสมิง',
  },
  {
      student_id: 67009,
      prefix: 'นางสาว',
      first_name: 'อรทัย',
      last_name: 'มณีแก้ว',
  },
  {
      student_id: 67010,
      prefix: 'นาย',
      first_name: 'จักรพงษ์',
      last_name: 'วัฒนชัย',
  },
  {
      student_id: 67011,
      prefix: 'นาย',
      first_name: 'ศุภชัย',
      last_name: 'รัตนไพศาล',
  },
  {
      student_id: 67012,
      prefix: 'นางสาว',
      first_name: 'สุพัตรา',
      last_name: 'จิตรเจริญ',
  },
  {
      student_id: 67013,
      prefix: 'นาย',
      first_name: 'สมคิด',
      last_name: 'ทองอร่าม',
  },
  {
      student_id: 67014,
      prefix: 'นาย',
      first_name: 'กิตติ',
      last_name: 'ชูแสง',
  },
  {
      student_id: 67015,
      prefix: 'นางสาว',
      first_name: 'รัชนี',
      last_name: 'แก้วคำ',
  },
  {
      student_id: 67016,
      prefix: 'นาย',
      first_name: 'วิทยา',
      last_name: 'ทองทิพย์',
  },
  {
      student_id: 67017,
      prefix: 'นางสาว',
      first_name: 'รุ่งทิวา',
      last_name: 'มณีวงศ์',
  },
  {
      student_id: 67018,
      prefix: 'นาย',
      first_name: 'มานพ',
      last_name: 'ศรีเจริญ',
  },
  {
      student_id: 67019,
      prefix: 'นางสาว',
      first_name: 'สุภาภรณ์',
      last_name: 'แก้วมณี',
  },
  {
      student_id: 67020,
      prefix: 'นาย',
      first_name: 'ธนกร',
      last_name: 'นวลจันทร์',
  },
  {
      student_id: 67021,
      prefix: 'นางสาว',
      first_name: 'พรทิพย์',
      last_name: 'พงษ์สวัสดิ์',
  },
  {
      student_id: 67022,
      prefix: 'นาย',
      first_name: 'สุกิจ',
      last_name: 'เพ็ญสุข',
  },
  {
      student_id: 67023,
      prefix: 'นางสาว',
      first_name: 'ปราณี',
      last_name: 'จิราวรรณ',
  },
  {
      student_id: 67024,
      prefix: 'นาย',
      first_name: 'เอกชัย',
      last_name: 'วัฒนสุข',
  },
  {
      student_id: 67025,
      prefix: 'นางสาว',
      first_name: 'อรวรรณ',
      last_name: 'รัตนวงศ์',
  },
  {
      student_id: 67026,
      prefix: 'นาย',
      first_name: 'จิราวัฒน์',
      last_name: 'ศรีทิพย์',
  },
  {
      student_id: 67027,
      prefix: 'นาย',
      first_name: 'สุวัฒน์',
      last_name: 'ทองสุข',
  },
  {
      student_id: 67028,
      prefix: 'นาย',
      first_name: 'นรินทร์',
      last_name: 'รัตนสกุล',
  },
  {
      student_id: 67029,
      prefix: 'นางสาว',
      first_name: 'พิมพ์พร',
      last_name: 'ศิริชัย',
  },
  {
      student_id: 67030,
      prefix: 'นาย',
      first_name: 'ชาญชัย',
      last_name: 'พงษ์ทิพย์',
  },
  {
      student_id: 67031,
      prefix: 'นางสาว',
      first_name: 'วิไล',
      last_name: 'ทองเจริญ',
  },
  {
      student_id: 67032,
      prefix: 'นาย',
      first_name: 'พิชัย',
      last_name: 'มณีวงศ์',
  },
  {
      student_id: 67033,
      prefix: 'นางสาว',
      first_name: 'รัชนีกร',
      last_name: 'ทองสุข',
  },
  {
      student_id: 67034,
      prefix: 'นาย',
      first_name: 'ภาณุ',
      last_name: 'รัตนจิต',
  },
  {
      student_id: 67035,
      prefix: 'นางสาว',
      first_name: 'นุชนารถ',
      last_name: 'ศรีประเสริฐ',
  },
  {
      student_id: 67036,
      prefix: 'นาย',
      first_name: 'อุดม',
      last_name: 'เพ็ญแสง',
  },
  {
      student_id: 67037,
      prefix: 'นาย',
      first_name: 'ประกอบ',
      last_name: 'วงศ์แก้ว',
  },
  {
      student_id: 67038,
      prefix: 'นางสาว',
      first_name: 'พิมพ์ใจ',
      last_name: 'จิราวรรณ',
  },
  {
      student_id: 67039,
      prefix: 'นาย',
      first_name: 'อดิศร',
      last_name: 'ศรีสวัสดิ์',
  },
  {
      student_id: 67040,
      prefix: 'นางสาว',
      first_name: 'วิมล',
      last_name: 'แก้วทอง',
  },
  {
      student_id: 67041,
      prefix: 'นาย',
      first_name: 'สราวุฒิ',
      last_name: 'ทองเจริญ',
  },
  {
      student_id: 67042,
      prefix: 'นางสาว',
      first_name: 'ดวงใจ',
      last_name: 'วัฒนวงศ์',
  },
  {
      student_id: 67043,
      prefix: 'นาย',
      first_name: 'สถาพร',
      last_name: 'มณีรัตน์',
  },
  {
      student_id: 67044,
      prefix: 'นางสาว',
      first_name: 'พัชรี',
      last_name: 'จิราพันธ์',
  },
  {
      student_id: 67045,
      prefix: 'นาย',
      first_name: 'สมยศ',
      last_name: 'ทองอร่าม',
  },
  {
      student_id: 67046,
      prefix: 'นางสาว',
      first_name: 'นภัส',
      last_name: 'รัตนมณี',
  },
  {
      student_id: 67047,
      prefix: 'นาย',
      first_name: 'วิทูร',
      last_name: 'วัฒนสกุล',
  },
  {
      student_id: 67048,
      prefix: 'นาย',
      first_name: 'ชัยรัตน์',
      last_name: 'ทองวงศ์',
  },
  {
      student_id: 67049,
      prefix: 'นางสาว',
      first_name: 'ชุติมา',
      last_name: 'มณีชัย',
  },
  {
      student_id: 67050,
      prefix: 'นางสาว',
      first_name: 'นฤมล',
      last_name: 'รัตนเจริญ',
  },
  {
      student_id: 67051,
      prefix: 'นาย',
      first_name: 'พิชิต',
      last_name: 'ทองแสง',
  },
  {
      student_id: 67052,
      prefix: 'นางสาว',
      first_name: 'นันทพร',
      last_name: 'วงศ์ประเสริฐ',
  },
  {
      student_id: 67053,
      prefix: 'นาย',
      first_name: 'ก้องเกียรติ',
      last_name: 'ศรีวงศ์',
  },
  {
      student_id: 67054,
      prefix: 'นาย',
      first_name: 'วีรพล',
      last_name: 'ทองจันทร์',
  },
  {
      student_id: 67055,
      prefix: 'นาย',
      first_name: 'ธเนศ',
      last_name: 'มณีทิพย์',
  },
  {
      student_id: 67056,
      prefix: 'นางสาว',
      first_name: 'ปราณีต',
      last_name: 'รัตนแสง',
  },
  {
      student_id: 67057,
      prefix: 'นางสาว',
      first_name: 'อัมพร',
      last_name: 'วัฒนสุข',
  },
  {
      student_id: 67058,
      prefix: 'นาย',
      first_name: 'วีรภัทร',
      last_name: 'ศรีทิพย์',
  },
  {
      student_id: 67059,
      prefix: 'นางสาว',
      first_name: 'สุวรรณา',
      last_name: 'ทองคำ',
  },
  {
      student_id: 67060,
      prefix: 'นาย',
      first_name: 'ศิริชัย',
      last_name: 'รัตนเพ็ญ',
  },
  {
      student_id: 67061,
      prefix: 'นาย',
      first_name: 'ปรีดา',
      last_name: 'แก้ววงศ์',
  },
  {
      student_id: 67062,
      prefix: 'นาย',
      first_name: 'ชาญณรงค์',
      last_name: 'ศรีเจริญ',
  },
  {
      student_id: 67063,
      prefix: 'นางสาว',
      first_name: 'วรรณา',
      last_name: 'ทองเพ็ญ',
  },
  {
      student_id: 67064,
      prefix: 'นาย',
      first_name: 'สุพจน์',
      last_name: 'รัตนประเสริฐ',
  },
  {
      student_id: 67065,
      prefix: 'นาย',
      first_name: 'ธนภัทร',
      last_name: 'วงศ์สวัสดิ์',
  },
  {
      student_id: 67066,
      prefix: 'นาย',
      first_name: 'กฤษฎา',
      last_name: 'ทองวงศ์',
  },
  {
      student_id: 67067,
      prefix: 'นาย',
      first_name: 'มนูญ',
      last_name: 'มณีรัตน์',
  },
  {
      student_id: 67068,
      prefix: 'นางสาว',
      first_name: 'พิมพ์ศิริ',
      last_name: 'รัตนเพ็ญ',
  },
  {
      student_id: 67069,
      prefix: 'นาย',
      first_name: 'ดำรง',
      last_name: 'ศรีวงศ์',
  },
  {
      student_id: 67070,
      prefix: 'นางสาว',
      first_name: 'รัตนา',
      last_name: 'วัฒนศิลป์',
  },
  {
      student_id: 67071,
      prefix: 'นาย',
      first_name: 'ประทุม',
      last_name: 'ทองเจริญ',
  },
  {
      student_id: 67072,
      prefix: 'นาย',
      first_name: 'พรชัย',
      last_name: 'รัตนมณี',
  },
  {
      student_id: 67073,
      prefix: 'นางสาว',
      first_name: 'สุนิสา',
      last_name: 'ทองวรรณ',
  },
  {
      student_id: 67074,
      prefix: 'นาย',
      first_name: 'ธวัช',
      last_name: 'ศรีสุข',
  },
  {
      student_id: 67075,
      prefix: 'นางสาว',
      first_name: 'สาวิตรี',
      last_name: 'มณีวงศ์',
  },
  {
      student_id: 67076,
      prefix: 'นาย',
      first_name: 'อนันต์',
      last_name: 'รัตนพงศ์',
  },
  {
      student_id: 67077,
      prefix: 'นาย',
      first_name: 'ธนพล',
      last_name: 'วงศ์เจริญ',
  },
  {
      student_id: 67078,
      prefix: 'นางสาว',
      first_name: 'ณัฐพร',
      last_name: 'ทองดี',
  },
  {
      student_id: 67079,
      prefix: 'นางสาว',
      first_name: 'ปัทมา',
      last_name: 'ศรีจันทร์',
  },
  {
      student_id: 67080,
      prefix: 'นาย',
      first_name: 'จักรกฤษณ์',
      last_name: 'รัตนแสง',
  },
  {
      student_id: 67081,
      prefix: 'นางสาว',
      first_name: 'ชลลดา',
      last_name: 'ทองจันทร์',
  },
  {
      student_id: 67082,
      prefix: 'นาย',
      first_name: 'อภิชัย',
      last_name: 'วัฒนวงศ์',
  },
  {
      student_id: 67083,
      prefix: 'นาย',
      first_name: 'วิชชา',
      last_name: 'มณีรัตน์',
  },
  {
      student_id: 67084,
      prefix: 'นาย',
      first_name: 'พงษ์เทพ',
      last_name: 'ทองแสง',
  },
  {
      student_id: 67085,
      prefix: 'นางสาว',
      first_name: 'ดวงพร',
      last_name: 'ศรีประเสริฐ',
  },
  {
      student_id: 67086,
      prefix: 'นาย',
      first_name: 'รุ่งโรจน์',
      last_name: 'รัตนวงศ์',
  },
  {
      student_id: 67087,
      prefix: 'นาย',
      first_name: 'ณรงค์ชัย',
      last_name: 'วงศ์สวัสดิ์',
  },
  {
      student_id: 67088,
      prefix: 'นางสาว',
      first_name: 'เพ็ญศรี',
      last_name: 'ศรีสกุล',
  },
  {
      student_id: 67089,
      prefix: 'นาย',
      first_name: 'วีระชัย',
      last_name: 'ทองวรรณ',
  },
  {
      student_id: 67090,
      prefix: 'นางสาว',
      first_name: 'พรพิมล',
      last_name: 'วัฒนสกุล',
  },
  {
      student_id: 67091,
      prefix: 'นาย',
      first_name: 'สมพร',
      last_name: 'ศรีทิพย์',
  },
  {
      student_id: 67092,
      prefix: 'นาย',
      first_name: 'ศิริพงษ์',
      last_name: 'ทองแสง',
  },
  {
      student_id: 67093,
      prefix: 'นาย',
      first_name: 'ชุมพล',
      last_name: 'รัตนพงศ์',
  },
  {
      student_id: 67094,
      prefix: 'นางสาว',
      first_name: 'สราวรรณ',
      last_name: 'วัฒนวงศ์',
  },
  {
      student_id: 67095,
      prefix: 'นาย',
      first_name: 'สุดใจ',
      last_name: 'ทองคำ',
  },
  {
      student_id: 67096,
      prefix: 'นาย',
      first_name: 'ยศศักดิ์',
      last_name: 'แสงทอง',
  },
  {
      student_id: 67097,
      prefix: 'นาย',
      first_name: 'นพพร',
      last_name: 'ทองวงศ์',
  },
  {
      student_id: 67098,
      prefix: 'นาย',
      first_name: 'ศุภกาญจน์',
      last_name: 'วัฒนแสง',
  },
  {
      student_id: 67099,
      prefix: 'นาย',
      first_name: 'วินัย',
      last_name: 'รัตนสุข',
  },
  {
      student_id: 67100,
      prefix: 'นางสาว',
      first_name: 'สุนิสา',
      last_name: 'ทองวาว',
  }
];
